"""anwesend aus User entfernt. kommen und gehen in Buchungen zu boolean geändert

Revision ID: 45b880160936
Revises: 40ac4d8befdf
Create Date: 2022-11-22 14:17:30.788701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b880160936'
down_revision = '40ac4d8befdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.alter_column('kommen',
               existing_type=sa.DATETIME(),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('anwesend')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anwesend', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.alter_column('kommen',
               existing_type=sa.Boolean(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
