"""changed Buchungen table

Revision ID: c98b896c67f0
Revises: dd9f930453b9
Create Date: 2022-11-15 09:41:20.320670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c98b896c67f0"
down_revision = "dd9f930453b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("buchungen", schema=None) as batch_op:
        batch_op.add_column(sa.Column("kommen", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("gehen", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("buchungen", schema=None) as batch_op:
        batch_op.drop_column("gehen")
        batch_op.drop_column("kommen")

    # ### end Alembic commands ###
