"""User table

Revision ID: dd9f930453b9
Revises: 8b044a091fc2
Create Date: 2022-11-15 08:53:11.644611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd9f930453b9"
down_revision = "8b044a091fc2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("personalnummer", sa.Integer(), nullable=True))
        batch_op.drop_index("ix_user_user_code")
        batch_op.create_index(
            batch_op.f("ix_user_personalnummer"), ["personalnummer"], unique=True
        )
        batch_op.drop_column("user_code")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_code", sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_user_personalnummer"))
        batch_op.create_index("ix_user_user_code", ["user_code"], unique=False)
        batch_op.drop_column("personalnummer")

    # ### end Alembic commands ###
