"""empty message

Revision ID: e64adcaef4d9
Revises: f7517a79ea99
Create Date: 2022-11-25 09:50:13.658982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e64adcaef4d9"
down_revision = "f7517a79ea99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("anwesend", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("anwesend")

    # ### end Alembic commands ###
