"""anwesend Spalte weg, kommen und gehen zu bool geändert

Revision ID: f7517a79ea99
Revises: 45b880160936
Create Date: 2022-11-22 15:20:44.376697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7517a79ea99'
down_revision = '45b880160936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.alter_column('gehen',
               existing_type=sa.DATETIME(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.alter_column('gehen',
               existing_type=sa.Boolean(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
